/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class btDiscreteDynamicsWorld
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h"


/** Cast (class_name)
 * 
 */
static int btDiscreteDynamicsWorld__cast_(lua_State *L) {

  btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata_n(L, 1, "bt.DiscreteDynamicsWorld"));
  const char *key = luaL_checkstring(L, 2);
  void **retval__ = (void**)lua_newuserdata(L, sizeof(void*));
  int key_h = dub_hash(key, 3);
  switch(key_h) {
    case 0: {
      if (DUB_ASSERT_KEY(key, "bt.DynamicsWorld")) break;
      *retval__ = static_cast<btDynamicsWorld *>(self);
      return 1;
    }
    case 1: {
      if (DUB_ASSERT_KEY(key, "bt.CollisionWorld")) break;
      *retval__ = static_cast<btCollisionWorld *>(self);
      return 1;
    }
  }
  return 0;
}

/** btDiscreteDynamicsWorld::btDiscreteDynamicsWorld(btDispatcher *dispatcher, btBroadphaseInterface *pairCache, btConstraintSolver *constraintSolver, btCollisionConfiguration *collisionConfiguration)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:99
 */
static int btDiscreteDynamicsWorld_btDiscreteDynamicsWorld(lua_State *L) {
  try {
    btDispatcher *dispatcher = *((btDispatcher **)dub_checksdata(L, 1, "bt.Dispatcher"));
    btBroadphaseInterface *pairCache = *((btBroadphaseInterface **)dub_checksdata(L, 2, "bt.BroadphaseInterface"));
    btConstraintSolver *constraintSolver = *((btConstraintSolver **)dub_checksdata(L, 3, "bt.ConstraintSolver"));
    btCollisionConfiguration *collisionConfiguration = *((btCollisionConfiguration **)dub_checksdata(L, 4, "bt.CollisionConfiguration"));
    btDiscreteDynamicsWorld *retval__ = new btDiscreteDynamicsWorld(dispatcher, pairCache, constraintSolver, collisionConfiguration);
    dub_pushudata(L, retval__, "bt.DiscreteDynamicsWorld", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "btDiscreteDynamicsWorld: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "btDiscreteDynamicsWorld: Unknown exception");
  }
  return dub_error(L);
}

/** virtual btDiscreteDynamicsWorld::~btDiscreteDynamicsWorld()
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:101
 */
static int btDiscreteDynamicsWorld__btDiscreteDynamicsWorld(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub_checksdata_d(L, 1, "bt.DiscreteDynamicsWorld"));
    if (userdata->gc) {
      btDiscreteDynamicsWorld *self = (btDiscreteDynamicsWorld *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "~btDiscreteDynamicsWorld: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "~btDiscreteDynamicsWorld: Unknown exception");
  }
  return dub_error(L);
}

/** virtual int btDiscreteDynamicsWorld::stepSimulation(btScalar timeStep, int maxSubSteps=1, btScalar fixedTimeStep=btScalar(1.)/btScalar(60.))
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:104
 */
static int btDiscreteDynamicsWorld_stepSimulation(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    int top__ = lua_gettop(L);
    if (top__ >= 4) {
      btScalar timeStep = dub_checknumber(L, 2);
      int maxSubSteps = dub_checkint(L, 3);
      btScalar fixedTimeStep = dub_checknumber(L, 4);
      lua_pushnumber(L, self->stepSimulation(timeStep, maxSubSteps, fixedTimeStep));
      return 1;
    } else if (top__ >= 3) {
      btScalar timeStep = dub_checknumber(L, 2);
      int maxSubSteps = dub_checkint(L, 3);
      lua_pushnumber(L, self->stepSimulation(timeStep, maxSubSteps));
      return 1;
    } else {
      btScalar timeStep = dub_checknumber(L, 2);
      lua_pushnumber(L, self->stepSimulation(timeStep));
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "stepSimulation: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "stepSimulation: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void btDiscreteDynamicsWorld::synchronizeMotionStates()
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:107
 */
static int btDiscreteDynamicsWorld_synchronizeMotionStates(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    self->synchronizeMotionStates();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "synchronizeMotionStates: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "synchronizeMotionStates: Unknown exception");
  }
  return dub_error(L);
}

/** void btDiscreteDynamicsWorld::synchronizeSingleMotionState(btRigidBody *body)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:110
 */
static int btDiscreteDynamicsWorld_synchronizeSingleMotionState(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    btRigidBody *body = *((btRigidBody **)dub_checksdata(L, 2, "bt.RigidBody"));
    self->synchronizeSingleMotionState(body);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "synchronizeSingleMotionState: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "synchronizeSingleMotionState: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void btDiscreteDynamicsWorld::addConstraint(btTypedConstraint *constraint, bool disableCollisionsBetweenLinkedBodies=false)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:112
 */
static int btDiscreteDynamicsWorld_addConstraint(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    int top__ = lua_gettop(L);
    if (top__ >= 3) {
      btTypedConstraint *constraint = *((btTypedConstraint **)dub_checksdata(L, 2, "TypedConstraint *"));
      bool disableCollisionsBetweenLinkedBodies = dub_checkboolean(L, 3);
      self->addConstraint(constraint, disableCollisionsBetweenLinkedBodies);
      return 0;
    } else {
      btTypedConstraint *constraint = *((btTypedConstraint **)dub_checksdata(L, 2, "TypedConstraint *"));
      self->addConstraint(constraint);
      return 0;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "addConstraint: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "addConstraint: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void btDiscreteDynamicsWorld::removeConstraint(btTypedConstraint *constraint)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:114
 */
static int btDiscreteDynamicsWorld_removeConstraint(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    btTypedConstraint *constraint = *((btTypedConstraint **)dub_checksdata(L, 2, "TypedConstraint *"));
    self->removeConstraint(constraint);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "removeConstraint: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "removeConstraint: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void btDiscreteDynamicsWorld::addAction(btActionInterface *)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:116
 */
static int btDiscreteDynamicsWorld_addAction(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    btActionInterface *p1 = *((btActionInterface **)dub_checksdata(L, 2, "ActionInterface *"));
    self->addAction(p1);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "addAction: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "addAction: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void btDiscreteDynamicsWorld::removeAction(btActionInterface *)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:118
 */
static int btDiscreteDynamicsWorld_removeAction(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    btActionInterface *p1 = *((btActionInterface **)dub_checksdata(L, 2, "ActionInterface *"));
    self->removeAction(p1);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "removeAction: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "removeAction: Unknown exception");
  }
  return dub_error(L);
}

/** btSimulationIslandManager* btDiscreteDynamicsWorld::getSimulationIslandManager()
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:121
 */
static int btDiscreteDynamicsWorld_getSimulationIslandManager(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    btSimulationIslandManager *retval__ = self->getSimulationIslandManager();
    if (!retval__) return 0;
    dub_pushudata(L, retval__, "SimulationIslandManager *", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getSimulationIslandManager: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getSimulationIslandManager: Unknown exception");
  }
  return dub_error(L);
}

/** btCollisionWorld* btDiscreteDynamicsWorld::getCollisionWorld()
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:131
 */
static int btDiscreteDynamicsWorld_getCollisionWorld(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    btCollisionWorld *retval__ = self->getCollisionWorld();
    if (!retval__) return 0;
    dub_pushudata(L, retval__, "CollisionWorld *", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getCollisionWorld: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getCollisionWorld: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void btDiscreteDynamicsWorld::setGravity(const btVector3 &gravity)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:135
 */
static int btDiscreteDynamicsWorld_setGravity(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    btVector3 *gravity = *((btVector3 **)dub_checksdata(L, 2, "bt.Vector3"));
    self->setGravity(*gravity);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setGravity: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setGravity: Unknown exception");
  }
  return dub_error(L);
}

/** virtual btVector3 btDiscreteDynamicsWorld::getGravity() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:137
 */
static int btDiscreteDynamicsWorld_getGravity(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    dub_pushudata(L, new btVector3(self->getGravity()), "bt.Vector3", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getGravity: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getGravity: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void btDiscreteDynamicsWorld::addCollisionObject(btCollisionObject *collisionObject, short int collisionFilterGroup=btBroadphaseProxy::StaticFilter, short int collisionFilterMask=btBroadphaseProxy::AllFilter^btBroadphaseProxy::StaticFilter)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:139
 */
static int btDiscreteDynamicsWorld_addCollisionObject(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    int top__ = lua_gettop(L);
    if (top__ >= 4) {
      btCollisionObject *collisionObject = *((btCollisionObject **)dub_checksdata(L, 2, "CollisionObject *"));
      short int *collisionFilterGroup = *((short int **)dub_checksdata(L, 3, "short int"));
      short int *collisionFilterMask = *((short int **)dub_checksdata(L, 4, "short int"));
      self->addCollisionObject(collisionObject, *collisionFilterGroup, *collisionFilterMask);
      return 0;
    } else if (top__ >= 3) {
      btCollisionObject *collisionObject = *((btCollisionObject **)dub_checksdata(L, 2, "CollisionObject *"));
      short int *collisionFilterGroup = *((short int **)dub_checksdata(L, 3, "short int"));
      self->addCollisionObject(collisionObject, *collisionFilterGroup);
      return 0;
    } else {
      btCollisionObject *collisionObject = *((btCollisionObject **)dub_checksdata(L, 2, "CollisionObject *"));
      self->addCollisionObject(collisionObject);
      return 0;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "addCollisionObject: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "addCollisionObject: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void btDiscreteDynamicsWorld::addRigidBody(btRigidBody *body)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:141
 */
static int btDiscreteDynamicsWorld_addRigidBody(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    int top__ = lua_gettop(L);
    if (top__ >= 4) {
      btRigidBody *body = *((btRigidBody **)dub_checksdata(L, 2, "bt.RigidBody"));
      short group = dub_checkint(L, 3);
      short mask = dub_checkint(L, 4);
      self->addRigidBody(body, group, mask);
      return 0;
    } else {
      btRigidBody *body = *((btRigidBody **)dub_checksdata(L, 2, "bt.RigidBody"));
      self->addRigidBody(body);
      return 0;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "addRigidBody: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "addRigidBody: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void btDiscreteDynamicsWorld::removeRigidBody(btRigidBody *body)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:145
 */
static int btDiscreteDynamicsWorld_removeRigidBody(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    btRigidBody *body = *((btRigidBody **)dub_checksdata(L, 2, "bt.RigidBody"));
    self->removeRigidBody(body);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "removeRigidBody: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "removeRigidBody: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void btDiscreteDynamicsWorld::removeCollisionObject(btCollisionObject *collisionObject)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:148
 */
static int btDiscreteDynamicsWorld_removeCollisionObject(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    btCollisionObject *collisionObject = *((btCollisionObject **)dub_checksdata(L, 2, "CollisionObject *"));
    self->removeCollisionObject(collisionObject);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "removeCollisionObject: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "removeCollisionObject: Unknown exception");
  }
  return dub_error(L);
}

/** void btDiscreteDynamicsWorld::debugDrawConstraint(btTypedConstraint *constraint)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:151
 */
static int btDiscreteDynamicsWorld_debugDrawConstraint(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    btTypedConstraint *constraint = *((btTypedConstraint **)dub_checksdata(L, 2, "TypedConstraint *"));
    self->debugDrawConstraint(constraint);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "debugDrawConstraint: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "debugDrawConstraint: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void btDiscreteDynamicsWorld::debugDrawWorld()
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:153
 */
static int btDiscreteDynamicsWorld_debugDrawWorld(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    self->debugDrawWorld();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "debugDrawWorld: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "debugDrawWorld: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void btDiscreteDynamicsWorld::setConstraintSolver(btConstraintSolver *solver)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:155
 */
static int btDiscreteDynamicsWorld_setConstraintSolver(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    btConstraintSolver *solver = *((btConstraintSolver **)dub_checksdata(L, 2, "bt.ConstraintSolver"));
    self->setConstraintSolver(solver);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setConstraintSolver: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setConstraintSolver: Unknown exception");
  }
  return dub_error(L);
}

/** virtual btConstraintSolver* btDiscreteDynamicsWorld::getConstraintSolver()
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:157
 */
static int btDiscreteDynamicsWorld_getConstraintSolver(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    btConstraintSolver *retval__ = self->getConstraintSolver();
    if (!retval__) return 0;
    dub_pushudata(L, retval__, "bt.ConstraintSolver", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getConstraintSolver: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getConstraintSolver: Unknown exception");
  }
  return dub_error(L);
}

/** virtual int btDiscreteDynamicsWorld::getNumConstraints() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:159
 */
static int btDiscreteDynamicsWorld_getNumConstraints(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    lua_pushnumber(L, self->getNumConstraints());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getNumConstraints: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getNumConstraints: Unknown exception");
  }
  return dub_error(L);
}

/** virtual btTypedConstraint* btDiscreteDynamicsWorld::getConstraint(int index)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:161
 */
static int btDiscreteDynamicsWorld_getConstraint(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    int index = dub_checkint(L, 2);
    btTypedConstraint *retval__ = self->getConstraint(index);
    if (!retval__) return 0;
    dub_pushudata(L, retval__, "TypedConstraint *", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getConstraint: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getConstraint: Unknown exception");
  }
  return dub_error(L);
}

/** virtual btDynamicsWorldType btDiscreteDynamicsWorld::getWorldType() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:167
 */
static int btDiscreteDynamicsWorld_getWorldType(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    lua_pushnumber(L, self->getWorldType());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getWorldType: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getWorldType: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void btDiscreteDynamicsWorld::clearForces()
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:172
 */
static int btDiscreteDynamicsWorld_clearForces(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    self->clearForces();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "clearForces: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "clearForces: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void btDiscreteDynamicsWorld::applyGravity()
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:175
 */
static int btDiscreteDynamicsWorld_applyGravity(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    self->applyGravity();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "applyGravity: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "applyGravity: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void btDiscreteDynamicsWorld::setNumTasks(int numTasks)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:178
 */
static int btDiscreteDynamicsWorld_setNumTasks(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    int numTasks = dub_checkint(L, 2);
    self->setNumTasks(numTasks);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setNumTasks: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setNumTasks: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void btDiscreteDynamicsWorld::updateVehicles(btScalar timeStep)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:184
 */
static int btDiscreteDynamicsWorld_updateVehicles(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    btScalar timeStep = dub_checknumber(L, 2);
    self->updateVehicles(timeStep);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "updateVehicles: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "updateVehicles: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void btDiscreteDynamicsWorld::addVehicle(btActionInterface *vehicle)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:189
 */
static int btDiscreteDynamicsWorld_addVehicle(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    btActionInterface *vehicle = *((btActionInterface **)dub_checksdata(L, 2, "ActionInterface *"));
    self->addVehicle(vehicle);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "addVehicle: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "addVehicle: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void btDiscreteDynamicsWorld::removeVehicle(btActionInterface *vehicle)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:191
 */
static int btDiscreteDynamicsWorld_removeVehicle(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    btActionInterface *vehicle = *((btActionInterface **)dub_checksdata(L, 2, "ActionInterface *"));
    self->removeVehicle(vehicle);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "removeVehicle: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "removeVehicle: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void btDiscreteDynamicsWorld::addCharacter(btActionInterface *character)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:193
 */
static int btDiscreteDynamicsWorld_addCharacter(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    btActionInterface *character = *((btActionInterface **)dub_checksdata(L, 2, "ActionInterface *"));
    self->addCharacter(character);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "addCharacter: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "addCharacter: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void btDiscreteDynamicsWorld::removeCharacter(btActionInterface *character)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:195
 */
static int btDiscreteDynamicsWorld_removeCharacter(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    btActionInterface *character = *((btActionInterface **)dub_checksdata(L, 2, "ActionInterface *"));
    self->removeCharacter(character);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "removeCharacter: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "removeCharacter: Unknown exception");
  }
  return dub_error(L);
}

/** void btDiscreteDynamicsWorld::setSynchronizeAllMotionStates(bool synchronizeAll)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:198
 */
static int btDiscreteDynamicsWorld_setSynchronizeAllMotionStates(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    bool synchronizeAll = dub_checkboolean(L, 2);
    self->setSynchronizeAllMotionStates(synchronizeAll);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setSynchronizeAllMotionStates: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setSynchronizeAllMotionStates: Unknown exception");
  }
  return dub_error(L);
}

/** bool btDiscreteDynamicsWorld::getSynchronizeAllMotionStates() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:202
 */
static int btDiscreteDynamicsWorld_getSynchronizeAllMotionStates(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    lua_pushboolean(L, self->getSynchronizeAllMotionStates());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getSynchronizeAllMotionStates: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getSynchronizeAllMotionStates: Unknown exception");
  }
  return dub_error(L);
}

/** void btDiscreteDynamicsWorld::setApplySpeculativeContactRestitution(bool enable)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:207
 */
static int btDiscreteDynamicsWorld_setApplySpeculativeContactRestitution(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    bool enable = dub_checkboolean(L, 2);
    self->setApplySpeculativeContactRestitution(enable);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setApplySpeculativeContactRestitution: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setApplySpeculativeContactRestitution: Unknown exception");
  }
  return dub_error(L);
}

/** bool btDiscreteDynamicsWorld::getApplySpeculativeContactRestitution() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:212
 */
static int btDiscreteDynamicsWorld_getApplySpeculativeContactRestitution(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    lua_pushboolean(L, self->getApplySpeculativeContactRestitution());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getApplySpeculativeContactRestitution: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getApplySpeculativeContactRestitution: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void btDiscreteDynamicsWorld::serialize(btSerializer *serializer)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:217
 */
static int btDiscreteDynamicsWorld_serialize(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    btSerializer *serializer = *((btSerializer **)dub_checksdata(L, 2, "Serializer *"));
    self->serialize(serializer);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "serialize: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "serialize: Unknown exception");
  }
  return dub_error(L);
}

/** void btDynamicsWorld::setInternalTickCallback(btInternalTickCallback cb, void *worldUserInfo=0, bool isPreTick=false)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDynamicsWorld.h:110
 */
static int btDiscreteDynamicsWorld_setInternalTickCallback(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    int top__ = lua_gettop(L);
    if (top__ >= 4) {
      btInternalTickCallback *cb = *((btInternalTickCallback **)dub_checksdata(L, 2, "InternalTickCallback *"));
      void *worldUserInfo = *((void **)dub_checksdata(L, 3, "void"));
      bool isPreTick = dub_checkboolean(L, 4);
      self->setInternalTickCallback(*cb, worldUserInfo, isPreTick);
      return 0;
    } else if (top__ >= 3) {
      btInternalTickCallback *cb = *((btInternalTickCallback **)dub_checksdata(L, 2, "InternalTickCallback *"));
      void *worldUserInfo = *((void **)dub_checksdata(L, 3, "void"));
      self->setInternalTickCallback(*cb, worldUserInfo);
      return 0;
    } else {
      btInternalTickCallback *cb = *((btInternalTickCallback **)dub_checksdata(L, 2, "InternalTickCallback *"));
      self->setInternalTickCallback(*cb);
      return 0;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "setInternalTickCallback: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setInternalTickCallback: Unknown exception");
  }
  return dub_error(L);
}

/** void btDynamicsWorld::setWorldUserInfo(void *worldUserInfo)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDynamicsWorld.h:122
 */
static int btDiscreteDynamicsWorld_setWorldUserInfo(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    void *worldUserInfo = *((void **)dub_checksdata(L, 2, "void"));
    self->setWorldUserInfo(worldUserInfo);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setWorldUserInfo: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setWorldUserInfo: Unknown exception");
  }
  return dub_error(L);
}

/** void* btDynamicsWorld::getWorldUserInfo() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDynamicsWorld.h:127
 */
static int btDiscreteDynamicsWorld_getWorldUserInfo(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    self->getWorldUserInfo();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getWorldUserInfo: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getWorldUserInfo: Unknown exception");
  }
  return dub_error(L);
}

/** btContactSolverInfo& btDynamicsWorld::getSolverInfo()
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btDynamicsWorld.h:132
 */
static int btDiscreteDynamicsWorld_getSolverInfo(lua_State *L) {
  try {
    btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata(L, 1, "bt.DiscreteDynamicsWorld"));
    dub_pushudata(L, &self->getSolverInfo(), "ContactSolverInfo", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getSolverInfo: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getSolverInfo: Unknown exception");
  }
  return dub_error(L);
}



// --=============================================== __tostring
static int btDiscreteDynamicsWorld___tostring(lua_State *L) {
  btDiscreteDynamicsWorld *self = *((btDiscreteDynamicsWorld **)dub_checksdata_n(L, 1, "bt.DiscreteDynamicsWorld"));
  lua_pushfstring(L, "bt.DiscreteDynamicsWorld: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg btDiscreteDynamicsWorld_member_methods[] = {
  { "_cast_"       , btDiscreteDynamicsWorld__cast_ },
  { "new"          , btDiscreteDynamicsWorld_btDiscreteDynamicsWorld },
  { "__gc"         , btDiscreteDynamicsWorld__btDiscreteDynamicsWorld },
  { "stepSimulation", btDiscreteDynamicsWorld_stepSimulation },
  { "synchronizeMotionStates", btDiscreteDynamicsWorld_synchronizeMotionStates },
  { "synchronizeSingleMotionState", btDiscreteDynamicsWorld_synchronizeSingleMotionState },
  { "addConstraint", btDiscreteDynamicsWorld_addConstraint },
  { "removeConstraint", btDiscreteDynamicsWorld_removeConstraint },
  { "addAction"    , btDiscreteDynamicsWorld_addAction },
  { "removeAction" , btDiscreteDynamicsWorld_removeAction },
  { "getSimulationIslandManager", btDiscreteDynamicsWorld_getSimulationIslandManager },
  { "getCollisionWorld", btDiscreteDynamicsWorld_getCollisionWorld },
  { "setGravity"   , btDiscreteDynamicsWorld_setGravity },
  { "getGravity"   , btDiscreteDynamicsWorld_getGravity },
  { "addCollisionObject", btDiscreteDynamicsWorld_addCollisionObject },
  { "addRigidBody" , btDiscreteDynamicsWorld_addRigidBody },
  { "removeRigidBody", btDiscreteDynamicsWorld_removeRigidBody },
  { "removeCollisionObject", btDiscreteDynamicsWorld_removeCollisionObject },
  { "debugDrawConstraint", btDiscreteDynamicsWorld_debugDrawConstraint },
  { "debugDrawWorld", btDiscreteDynamicsWorld_debugDrawWorld },
  { "setConstraintSolver", btDiscreteDynamicsWorld_setConstraintSolver },
  { "getConstraintSolver", btDiscreteDynamicsWorld_getConstraintSolver },
  { "getNumConstraints", btDiscreteDynamicsWorld_getNumConstraints },
  { "getConstraint", btDiscreteDynamicsWorld_getConstraint },
  { "getWorldType" , btDiscreteDynamicsWorld_getWorldType },
  { "clearForces"  , btDiscreteDynamicsWorld_clearForces },
  { "applyGravity" , btDiscreteDynamicsWorld_applyGravity },
  { "setNumTasks"  , btDiscreteDynamicsWorld_setNumTasks },
  { "updateVehicles", btDiscreteDynamicsWorld_updateVehicles },
  { "addVehicle"   , btDiscreteDynamicsWorld_addVehicle },
  { "removeVehicle", btDiscreteDynamicsWorld_removeVehicle },
  { "addCharacter" , btDiscreteDynamicsWorld_addCharacter },
  { "removeCharacter", btDiscreteDynamicsWorld_removeCharacter },
  { "setSynchronizeAllMotionStates", btDiscreteDynamicsWorld_setSynchronizeAllMotionStates },
  { "getSynchronizeAllMotionStates", btDiscreteDynamicsWorld_getSynchronizeAllMotionStates },
  { "setApplySpeculativeContactRestitution", btDiscreteDynamicsWorld_setApplySpeculativeContactRestitution },
  { "getApplySpeculativeContactRestitution", btDiscreteDynamicsWorld_getApplySpeculativeContactRestitution },
  { "serialize"    , btDiscreteDynamicsWorld_serialize },
  { "setInternalTickCallback", btDiscreteDynamicsWorld_setInternalTickCallback },
  { "setWorldUserInfo", btDiscreteDynamicsWorld_setWorldUserInfo },
  { "getWorldUserInfo", btDiscreteDynamicsWorld_getWorldUserInfo },
  { "getSolverInfo", btDiscreteDynamicsWorld_getSolverInfo },
  { "__tostring"   , btDiscreteDynamicsWorld___tostring },
  { "deleted"      , dub_isDeleted        },
  { NULL, NULL},
};


extern "C" int luaopen_bt_DiscreteDynamicsWorld(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "bt.DiscreteDynamicsWorld");
  // <mt>

  // register member methods
  luaL_register(L, NULL, btDiscreteDynamicsWorld_member_methods);
  // save meta-table in bt
  dub_register(L, "bt", "DiscreteDynamicsWorld", "DiscreteDynamicsWorld");
  // <mt>
  lua_pop(L, 1);
  return 0;
}
