/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class btRigidBody
 *
 * This file has been generated by dub 2.1.~.
 */
#include "dub/dub.h"
#include "BulletDynamics/Dynamics/btRigidBody.h"


/** Set attributes (key, value)
 * 
 */
static int btRigidBody__set_(lua_State *L) {

  btRigidBody *self = *((btRigidBody **)dub_checksdata_n(L, 1, "bt.RigidBody"));
  const char *key = luaL_checkstring(L, 2);
  int key_h = dub_hash(key, 3);
  switch(key_h) {
    case 1: {
      if (DUB_ASSERT_KEY(key, "m_contactSolverType")) break;
      self->m_contactSolverType = luaL_checkint(L, 3);
      return 0;
    }
    case 0: {
      if (DUB_ASSERT_KEY(key, "m_frictionSolverType")) break;
      self->m_frictionSolverType = luaL_checkint(L, 3);
      return 0;
    }
  }
  if (lua_istable(L, 1)) {
    lua_rawset(L, 1);
  } else {
    luaL_error(L, KEY_EXCEPTION_MSG, key);
  }
  return 0;
}

/** Get attributes (key)
 * 
 */
static int btRigidBody__get_(lua_State *L) {

  btRigidBody *self = *((btRigidBody **)dub_checksdata_n(L, 1, "bt.RigidBody", true));
  const char *key = luaL_checkstring(L, 2);
  // <self> "key" <mt>
  // rawget(mt, key)
  lua_pushvalue(L, 2);
  // <self> "key" <mt> "key"
  lua_rawget(L, -2);
  if (!lua_isnil(L, -1)) {
    // Found method.
    return 1;
  } else {
    // Not in mt = attribute access.
    lua_pop(L, 2);
  }
  int key_h = dub_hash(key, 3);
  switch(key_h) {
    case 1: {
      if (DUB_ASSERT_KEY(key, "m_contactSolverType")) break;
      lua_pushnumber(L, self->m_contactSolverType);
      return 1;
    }
    case 0: {
      if (DUB_ASSERT_KEY(key, "m_frictionSolverType")) break;
      lua_pushnumber(L, self->m_frictionSolverType);
      return 1;
    }
  }
  return 0;
}

/** btRigidBody::btRigidBody(const btRigidBodyConstructionInfo &constructionInfo)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:172
 */
static int btRigidBody_btRigidBody(lua_State *L) {
  try {
    int top__ = lua_gettop(L);
    if (top__ >= 4) {
      btScalar mass = dub_checknumber(L, 1);
      btMotionState *motionState = *((btMotionState **)dub_checksdata(L, 2, "bt.MotionState"));
      btCollisionShape *collisionShape = *((btCollisionShape **)dub_checksdata(L, 3, "bt.CollisionShape"));
      btVector3 *localInertia = *((btVector3 **)dub_checksdata(L, 4, "bt.Vector3"));
      btRigidBody *retval__ = new btRigidBody(mass, motionState, collisionShape, *localInertia);
      dub_pushudata(L, retval__, "bt.RigidBody", true);
      return 1;
    } else if (top__ >= 3) {
      btScalar mass = dub_checknumber(L, 1);
      btMotionState *motionState = *((btMotionState **)dub_checksdata(L, 2, "bt.MotionState"));
      btCollisionShape *collisionShape = *((btCollisionShape **)dub_checksdata(L, 3, "bt.CollisionShape"));
      btRigidBody *retval__ = new btRigidBody(mass, motionState, collisionShape);
      dub_pushudata(L, retval__, "bt.RigidBody", true);
      return 1;
    } else {
      btRigidBody::btRigidBodyConstructionInfo *constructionInfo = *((btRigidBody::btRigidBodyConstructionInfo **)dub_checksdata(L, 1, "bt.RigidBody.RigidBodyConstructionInfo"));
      btRigidBody *retval__ = new btRigidBody(*constructionInfo);
      dub_pushudata(L, retval__, "bt.RigidBody", true);
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "btRigidBody: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "btRigidBody: Unknown exception");
  }
  return dub_error(L);
}

/** virtual btRigidBody::~btRigidBody()
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:180
 */
static int btRigidBody__btRigidBody(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub_checksdata_d(L, 1, "bt.RigidBody"));
    if (userdata->gc) {
      btRigidBody *self = (btRigidBody *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "~btRigidBody: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "~btRigidBody: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::proceedToTransform(const btTransform &newTrans)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:193
 */
static int btRigidBody_proceedToTransform(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btTransform *newTrans = *((btTransform **)dub_checksdata(L, 2, "bt.Transform"));
    self->proceedToTransform(*newTrans);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "proceedToTransform: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "proceedToTransform: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::predictIntegratedTransform(btScalar step, btTransform &predictedTransform)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:211
 */
static int btRigidBody_predictIntegratedTransform(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btScalar step = dub_checknumber(L, 2);
    btTransform *predictedTransform = *((btTransform **)dub_checksdata(L, 3, "bt.Transform"));
    self->predictIntegratedTransform(step, *predictedTransform);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "predictIntegratedTransform: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "predictIntegratedTransform: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::saveKinematicState(btScalar step)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:213
 */
static int btRigidBody_saveKinematicState(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btScalar step = dub_checknumber(L, 2);
    self->saveKinematicState(step);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "saveKinematicState: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "saveKinematicState: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::applyGravity()
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:215
 */
static int btRigidBody_applyGravity(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    self->applyGravity();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "applyGravity: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "applyGravity: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::setGravity(const btVector3 &acceleration)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:217
 */
static int btRigidBody_setGravity(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btVector3 *acceleration = *((btVector3 **)dub_checksdata(L, 2, "bt.Vector3"));
    self->setGravity(*acceleration);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setGravity: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setGravity: Unknown exception");
  }
  return dub_error(L);
}

/** const btVector3& btRigidBody::getGravity() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:220
 */
static int btRigidBody_getGravity(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    dub_pushudata(L, const_cast<btVector3*>(&self->getGravity()), "bt.Vector3", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getGravity: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getGravity: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::setDamping(btScalar lin_damping, btScalar ang_damping)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:224
 */
static int btRigidBody_setDamping(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btScalar lin_damping = dub_checknumber(L, 2);
    btScalar ang_damping = dub_checknumber(L, 3);
    self->setDamping(lin_damping, ang_damping);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setDamping: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setDamping: Unknown exception");
  }
  return dub_error(L);
}

/** btScalar btRigidBody::getLinearDamping() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:227
 */
static int btRigidBody_getLinearDamping(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    lua_pushnumber(L, self->getLinearDamping());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getLinearDamping: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getLinearDamping: Unknown exception");
  }
  return dub_error(L);
}

/** btScalar btRigidBody::getAngularDamping() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:232
 */
static int btRigidBody_getAngularDamping(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    lua_pushnumber(L, self->getAngularDamping());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getAngularDamping: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getAngularDamping: Unknown exception");
  }
  return dub_error(L);
}

/** btScalar btRigidBody::getLinearSleepingThreshold() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:237
 */
static int btRigidBody_getLinearSleepingThreshold(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    lua_pushnumber(L, self->getLinearSleepingThreshold());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getLinearSleepingThreshold: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getLinearSleepingThreshold: Unknown exception");
  }
  return dub_error(L);
}

/** btScalar btRigidBody::getAngularSleepingThreshold() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:242
 */
static int btRigidBody_getAngularSleepingThreshold(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    lua_pushnumber(L, self->getAngularSleepingThreshold());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getAngularSleepingThreshold: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getAngularSleepingThreshold: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::applyDamping(btScalar timeStep)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:246
 */
static int btRigidBody_applyDamping(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btScalar timeStep = dub_checknumber(L, 2);
    self->applyDamping(timeStep);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "applyDamping: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "applyDamping: Unknown exception");
  }
  return dub_error(L);
}

/** const btCollisionShape* btRigidBody::getCollisionShape() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:248
 */
static int btRigidBody_getCollisionShape(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    const btCollisionShape *retval__ = self->getCollisionShape();
    if (!retval__) return 0;
    dub_pushudata(L, const_cast<btCollisionShape*>(retval__), "bt.CollisionShape", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getCollisionShape: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getCollisionShape: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::setMassProps(btScalar mass, const btVector3 &inertia)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:256
 */
static int btRigidBody_setMassProps(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btScalar mass = dub_checknumber(L, 2);
    btVector3 *inertia = *((btVector3 **)dub_checksdata(L, 3, "bt.Vector3"));
    self->setMassProps(mass, *inertia);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setMassProps: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setMassProps: Unknown exception");
  }
  return dub_error(L);
}

/** const btVector3& btRigidBody::getLinearFactor() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:259
 */
static int btRigidBody_getLinearFactor(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    dub_pushudata(L, const_cast<btVector3*>(&self->getLinearFactor()), "bt.Vector3", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getLinearFactor: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getLinearFactor: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::setLinearFactor(const btVector3 &linearFactor)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:263
 */
static int btRigidBody_setLinearFactor(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btVector3 *linearFactor = *((btVector3 **)dub_checksdata(L, 2, "bt.Vector3"));
    self->setLinearFactor(*linearFactor);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setLinearFactor: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setLinearFactor: Unknown exception");
  }
  return dub_error(L);
}

/** btScalar btRigidBody::getInvMass() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:267
 */
static int btRigidBody_getInvMass(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    lua_pushnumber(L, self->getInvMass());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getInvMass: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getInvMass: Unknown exception");
  }
  return dub_error(L);
}

/** const btMatrix3x3& btRigidBody::getInvInertiaTensorWorld() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:268
 */
static int btRigidBody_getInvInertiaTensorWorld(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    dub_pushudata(L, const_cast<btMatrix3x3*>(&self->getInvInertiaTensorWorld()), "bt.Matrix3x3", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getInvInertiaTensorWorld: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getInvInertiaTensorWorld: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::integrateVelocities(btScalar step)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:272
 */
static int btRigidBody_integrateVelocities(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btScalar step = dub_checknumber(L, 2);
    self->integrateVelocities(step);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "integrateVelocities: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "integrateVelocities: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::setCenterOfMassTransform(const btTransform &xform)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:274
 */
static int btRigidBody_setCenterOfMassTransform(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btTransform *xform = *((btTransform **)dub_checksdata(L, 2, "bt.Transform"));
    self->setCenterOfMassTransform(*xform);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setCenterOfMassTransform: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setCenterOfMassTransform: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::applyCentralForce(const btVector3 &force)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:277
 */
static int btRigidBody_applyCentralForce(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btVector3 *force = *((btVector3 **)dub_checksdata(L, 2, "bt.Vector3"));
    self->applyCentralForce(*force);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "applyCentralForce: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "applyCentralForce: Unknown exception");
  }
  return dub_error(L);
}

/** const btVector3& btRigidBody::getTotalForce() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:282
 */
static int btRigidBody_getTotalForce(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    dub_pushudata(L, const_cast<btVector3*>(&self->getTotalForce()), "bt.Vector3", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getTotalForce: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getTotalForce: Unknown exception");
  }
  return dub_error(L);
}

/** const btVector3& btRigidBody::getTotalTorque() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:287
 */
static int btRigidBody_getTotalTorque(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    dub_pushudata(L, const_cast<btVector3*>(&self->getTotalTorque()), "bt.Vector3", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getTotalTorque: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getTotalTorque: Unknown exception");
  }
  return dub_error(L);
}

/** const btVector3& btRigidBody::getInvInertiaDiagLocal() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:292
 */
static int btRigidBody_getInvInertiaDiagLocal(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    dub_pushudata(L, const_cast<btVector3*>(&self->getInvInertiaDiagLocal()), "bt.Vector3", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getInvInertiaDiagLocal: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getInvInertiaDiagLocal: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::setInvInertiaDiagLocal(const btVector3 &diagInvInertia)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:297
 */
static int btRigidBody_setInvInertiaDiagLocal(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btVector3 *diagInvInertia = *((btVector3 **)dub_checksdata(L, 2, "bt.Vector3"));
    self->setInvInertiaDiagLocal(*diagInvInertia);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setInvInertiaDiagLocal: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setInvInertiaDiagLocal: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::setSleepingThresholds(btScalar linear, btScalar angular)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:302
 */
static int btRigidBody_setSleepingThresholds(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btScalar linear = dub_checknumber(L, 2);
    btScalar angular = dub_checknumber(L, 3);
    self->setSleepingThresholds(linear, angular);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setSleepingThresholds: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setSleepingThresholds: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::applyTorque(const btVector3 &torque)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:308
 */
static int btRigidBody_applyTorque(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btVector3 *torque = *((btVector3 **)dub_checksdata(L, 2, "bt.Vector3"));
    self->applyTorque(*torque);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "applyTorque: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "applyTorque: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::applyForce(const btVector3 &force, const btVector3 &rel_pos)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:313
 */
static int btRigidBody_applyForce(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btVector3 *force = *((btVector3 **)dub_checksdata(L, 2, "bt.Vector3"));
    btVector3 *rel_pos = *((btVector3 **)dub_checksdata(L, 3, "bt.Vector3"));
    self->applyForce(*force, *rel_pos);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "applyForce: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "applyForce: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::applyCentralImpulse(const btVector3 &impulse)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:319
 */
static int btRigidBody_applyCentralImpulse(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btVector3 *impulse = *((btVector3 **)dub_checksdata(L, 2, "bt.Vector3"));
    self->applyCentralImpulse(*impulse);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "applyCentralImpulse: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "applyCentralImpulse: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::applyTorqueImpulse(const btVector3 &torque)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:324
 */
static int btRigidBody_applyTorqueImpulse(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btVector3 *torque = *((btVector3 **)dub_checksdata(L, 2, "bt.Vector3"));
    self->applyTorqueImpulse(*torque);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "applyTorqueImpulse: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "applyTorqueImpulse: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::applyImpulse(const btVector3 &impulse, const btVector3 &rel_pos)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:329
 */
static int btRigidBody_applyImpulse(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btVector3 *impulse = *((btVector3 **)dub_checksdata(L, 2, "bt.Vector3"));
    btVector3 *rel_pos = *((btVector3 **)dub_checksdata(L, 3, "bt.Vector3"));
    self->applyImpulse(*impulse, *rel_pos);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "applyImpulse: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "applyImpulse: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::clearForces()
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:341
 */
static int btRigidBody_clearForces(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    self->clearForces();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "clearForces: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "clearForces: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::updateInertiaTensor()
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:346
 */
static int btRigidBody_updateInertiaTensor(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    self->updateInertiaTensor();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "updateInertiaTensor: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "updateInertiaTensor: Unknown exception");
  }
  return dub_error(L);
}

/** const btVector3& btRigidBody::getCenterOfMassPosition() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:348
 */
static int btRigidBody_getCenterOfMassPosition(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    dub_pushudata(L, const_cast<btVector3*>(&self->getCenterOfMassPosition()), "bt.Vector3", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getCenterOfMassPosition: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getCenterOfMassPosition: Unknown exception");
  }
  return dub_error(L);
}

/** btQuaternion btRigidBody::getOrientation() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:351
 */
static int btRigidBody_getOrientation(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    dub_pushudata(L, new btQuaternion(self->getOrientation()), "bt.Quaternion", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getOrientation: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getOrientation: Unknown exception");
  }
  return dub_error(L);
}

/** const btTransform& btRigidBody::getCenterOfMassTransform() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:353
 */
static int btRigidBody_getCenterOfMassTransform(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    dub_pushudata(L, const_cast<btTransform*>(&self->getCenterOfMassTransform()), "bt.Transform", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getCenterOfMassTransform: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getCenterOfMassTransform: Unknown exception");
  }
  return dub_error(L);
}

/** const btVector3& btRigidBody::getLinearVelocity() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:356
 */
static int btRigidBody_getLinearVelocity(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    dub_pushudata(L, const_cast<btVector3*>(&self->getLinearVelocity()), "bt.Vector3", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getLinearVelocity: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getLinearVelocity: Unknown exception");
  }
  return dub_error(L);
}

/** const btVector3& btRigidBody::getAngularVelocity() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:359
 */
static int btRigidBody_getAngularVelocity(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    dub_pushudata(L, const_cast<btVector3*>(&self->getAngularVelocity()), "bt.Vector3", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getAngularVelocity: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getAngularVelocity: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::setLinearVelocity(const btVector3 &lin_vel)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:365
 */
static int btRigidBody_setLinearVelocity(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btVector3 *lin_vel = *((btVector3 **)dub_checksdata(L, 2, "bt.Vector3"));
    self->setLinearVelocity(*lin_vel);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setLinearVelocity: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setLinearVelocity: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::setAngularVelocity(const btVector3 &ang_vel)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:370
 */
static int btRigidBody_setAngularVelocity(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btVector3 *ang_vel = *((btVector3 **)dub_checksdata(L, 2, "bt.Vector3"));
    self->setAngularVelocity(*ang_vel);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setAngularVelocity: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setAngularVelocity: Unknown exception");
  }
  return dub_error(L);
}

/** btVector3 btRigidBody::getVelocityInLocalPoint(const btVector3 &rel_pos) const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:375
 */
static int btRigidBody_getVelocityInLocalPoint(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btVector3 *rel_pos = *((btVector3 **)dub_checksdata(L, 2, "bt.Vector3"));
    dub_pushudata(L, new btVector3(self->getVelocityInLocalPoint(*rel_pos)), "bt.Vector3", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getVelocityInLocalPoint: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getVelocityInLocalPoint: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::translate(const btVector3 &v)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:384
 */
static int btRigidBody_translate(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btVector3 *v = *((btVector3 **)dub_checksdata(L, 2, "bt.Vector3"));
    self->translate(*v);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "translate: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "translate: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::getAabb(btVector3 &aabbMin, btVector3 &aabbMax) const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:389
 */
static int btRigidBody_getAabb(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btVector3 *aabbMin = *((btVector3 **)dub_checksdata(L, 2, "bt.Vector3"));
    btVector3 *aabbMax = *((btVector3 **)dub_checksdata(L, 3, "bt.Vector3"));
    self->getAabb(*aabbMin, *aabbMax);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getAabb: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getAabb: Unknown exception");
  }
  return dub_error(L);
}

/** btScalar btRigidBody::computeImpulseDenominator(const btVector3 &pos, const btVector3 &normal) const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:396
 */
static int btRigidBody_computeImpulseDenominator(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btVector3 *pos = *((btVector3 **)dub_checksdata(L, 2, "bt.Vector3"));
    btVector3 *normal = *((btVector3 **)dub_checksdata(L, 3, "bt.Vector3"));
    lua_pushnumber(L, self->computeImpulseDenominator(*pos, *normal));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "computeImpulseDenominator: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "computeImpulseDenominator: Unknown exception");
  }
  return dub_error(L);
}

/** btScalar btRigidBody::computeAngularImpulseDenominator(const btVector3 &axis) const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:408
 */
static int btRigidBody_computeAngularImpulseDenominator(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btVector3 *axis = *((btVector3 **)dub_checksdata(L, 2, "bt.Vector3"));
    lua_pushnumber(L, self->computeAngularImpulseDenominator(*axis));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "computeAngularImpulseDenominator: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "computeAngularImpulseDenominator: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::updateDeactivation(btScalar timeStep)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:414
 */
static int btRigidBody_updateDeactivation(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btScalar timeStep = dub_checknumber(L, 2);
    self->updateDeactivation(timeStep);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "updateDeactivation: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "updateDeactivation: Unknown exception");
  }
  return dub_error(L);
}

/** bool btRigidBody::wantsSleeping()
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:431
 */
static int btRigidBody_wantsSleeping(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    lua_pushboolean(L, self->wantsSleeping());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "wantsSleeping: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "wantsSleeping: Unknown exception");
  }
  return dub_error(L);
}

/** const btBroadphaseProxy* btRigidBody::getBroadphaseProxy() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:453
 */
static int btRigidBody_getBroadphaseProxy(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    const btBroadphaseProxy *retval__ = self->getBroadphaseProxy();
    if (!retval__) return 0;
    dub_pushudata(L, const_cast<btBroadphaseProxy*>(retval__), "BroadphaseProxy", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getBroadphaseProxy: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getBroadphaseProxy: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::setNewBroadphaseProxy(btBroadphaseProxy *broadphaseProxy)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:461
 */
static int btRigidBody_setNewBroadphaseProxy(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btBroadphaseProxy *broadphaseProxy = *((btBroadphaseProxy **)dub_checksdata(L, 2, "BroadphaseProxy"));
    self->setNewBroadphaseProxy(broadphaseProxy);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setNewBroadphaseProxy: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setNewBroadphaseProxy: Unknown exception");
  }
  return dub_error(L);
}

/** btMotionState* btRigidBody::getMotionState()
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:467
 */
static int btRigidBody_getMotionState(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btMotionState *retval__ = self->getMotionState();
    if (!retval__) return 0;
    dub_pushudata(L, retval__, "bt.MotionState", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getMotionState: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getMotionState: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::setMotionState(btMotionState *motionState)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:475
 */
static int btRigidBody_setMotionState(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btMotionState *motionState = *((btMotionState **)dub_checksdata(L, 2, "bt.MotionState"));
    self->setMotionState(motionState);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setMotionState: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setMotionState: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::setAngularFactor(const btVector3 &angFac)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:486
 */
static int btRigidBody_setAngularFactor(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    int type__ = lua_type(L, 2);
    if (type__ == LUA_TNUMBER) {
      btScalar angFac = dub_checknumber(L, 2);
      self->setAngularFactor(angFac);
      return 0;
    } else {
      btVector3 *angFac = *((btVector3 **)dub_checksdata(L, 2, "bt.Vector3"));
      self->setAngularFactor(*angFac);
      return 0;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "setAngularFactor: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setAngularFactor: Unknown exception");
  }
  return dub_error(L);
}

/** const btVector3& btRigidBody::getAngularFactor() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:495
 */
static int btRigidBody_getAngularFactor(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    dub_pushudata(L, const_cast<btVector3*>(&self->getAngularFactor()), "bt.Vector3", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getAngularFactor: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getAngularFactor: Unknown exception");
  }
  return dub_error(L);
}

/** bool btRigidBody::isInWorld() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:501
 */
static int btRigidBody_isInWorld(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    lua_pushboolean(L, self->isInWorld());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "isInWorld: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "isInWorld: Unknown exception");
  }
  return dub_error(L);
}

/** virtual bool btRigidBody::checkCollideWithOverride(const btCollisionObject *co) const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:505
 */
static int btRigidBody_checkCollideWithOverride(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btCollisionObject *co = *((btCollisionObject **)dub_checksdata(L, 2, "CollisionObject"));
    lua_pushboolean(L, self->checkCollideWithOverride(co));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "checkCollideWithOverride: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "checkCollideWithOverride: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::addConstraintRef(btTypedConstraint *c)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:507
 */
static int btRigidBody_addConstraintRef(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btTypedConstraint *c = *((btTypedConstraint **)dub_checksdata(L, 2, "TypedConstraint"));
    self->addConstraintRef(c);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "addConstraintRef: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "addConstraintRef: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::removeConstraintRef(btTypedConstraint *c)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:508
 */
static int btRigidBody_removeConstraintRef(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btTypedConstraint *c = *((btTypedConstraint **)dub_checksdata(L, 2, "TypedConstraint"));
    self->removeConstraintRef(c);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "removeConstraintRef: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "removeConstraintRef: Unknown exception");
  }
  return dub_error(L);
}

/** btTypedConstraint* btRigidBody::getConstraintRef(int index)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:511
 */
static int btRigidBody_getConstraintRef(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    int index = dub_checkint(L, 2);
    btTypedConstraint *retval__ = self->getConstraintRef(index);
    if (!retval__) return 0;
    dub_pushudata(L, retval__, "TypedConstraint", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getConstraintRef: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getConstraintRef: Unknown exception");
  }
  return dub_error(L);
}

/** int btRigidBody::getNumConstraintRefs() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:516
 */
static int btRigidBody_getNumConstraintRefs(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    lua_pushnumber(L, self->getNumConstraintRefs());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getNumConstraintRefs: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getNumConstraintRefs: Unknown exception");
  }
  return dub_error(L);
}

/** void btRigidBody::setFlags(int flags)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:521
 */
static int btRigidBody_setFlags(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    int flags = dub_checkint(L, 2);
    self->setFlags(flags);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setFlags: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setFlags: Unknown exception");
  }
  return dub_error(L);
}

/** int btRigidBody::getFlags() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:526
 */
static int btRigidBody_getFlags(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    lua_pushnumber(L, self->getFlags());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getFlags: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getFlags: Unknown exception");
  }
  return dub_error(L);
}

/** btVector3 btRigidBody::computeGyroscopicForce(btScalar maxGyroscopicForce) const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:530
 */
static int btRigidBody_computeGyroscopicForce(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    btScalar maxGyroscopicForce = dub_checknumber(L, 2);
    dub_pushudata(L, new btVector3(self->computeGyroscopicForce(maxGyroscopicForce)), "bt.Vector3", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "computeGyroscopicForce: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "computeGyroscopicForce: Unknown exception");
  }
  return dub_error(L);
}

/** virtual int btRigidBody::calculateSerializeBufferSize() const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:534
 */
static int btRigidBody_calculateSerializeBufferSize(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    lua_pushnumber(L, self->calculateSerializeBufferSize());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "calculateSerializeBufferSize: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "calculateSerializeBufferSize: Unknown exception");
  }
  return dub_error(L);
}

/** virtual const char* btRigidBody::serialize(void *dataBuffer, class btSerializer *serializer) const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:537
 */
static int btRigidBody_serialize(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    void *dataBuffer = *((void **)dub_checksdata(L, 2, "void"));
    class btSerializer *serializer = *((class btSerializer **)dub_checksdata(L, 3, "class btSerializer"));
    lua_pushstring(L, self->serialize(dataBuffer, serializer));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "serialize: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "serialize: Unknown exception");
  }
  return dub_error(L);
}

/** virtual void btRigidBody::serializeSingleObject(class btSerializer *serializer) const
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:539
 */
static int btRigidBody_serializeSingleObject(lua_State *L) {
  try {
    btRigidBody *self = *((btRigidBody **)dub_checksdata(L, 1, "bt.RigidBody"));
    class btSerializer *serializer = *((class btSerializer **)dub_checksdata(L, 2, "class btSerializer"));
    self->serializeSingleObject(serializer);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "serializeSingleObject: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "serializeSingleObject: Unknown exception");
  }
  return dub_error(L);
}

/** static const btRigidBody* btRigidBody::upcast(const btCollisionObject *colObj)
 * src/vendor/bullet/src/BulletDynamics/Dynamics/btRigidBody.h:198
 */
static int btRigidBody_upcast(lua_State *L) {
  try {
    btCollisionObject *colObj = *((btCollisionObject **)dub_checksdata(L, 1, "CollisionObject"));
    const btRigidBody *retval__ = btRigidBody::upcast(colObj);
    if (!retval__) return 0;
    dub_pushudata(L, const_cast<btRigidBody*>(retval__), "bt.RigidBody", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "upcast: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "upcast: Unknown exception");
  }
  return dub_error(L);
}



// --=============================================== __tostring
static int btRigidBody___tostring(lua_State *L) {
  btRigidBody *self = *((btRigidBody **)dub_checksdata_n(L, 1, "bt.RigidBody"));
  lua_pushfstring(L, "bt.RigidBody: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg btRigidBody_member_methods[] = {
  { "__newindex"   , btRigidBody__set_    },
  { "__index"      , btRigidBody__get_    },
  { "new"          , btRigidBody_btRigidBody },
  { "__gc"         , btRigidBody__btRigidBody },
  { "proceedToTransform", btRigidBody_proceedToTransform },
  { "predictIntegratedTransform", btRigidBody_predictIntegratedTransform },
  { "saveKinematicState", btRigidBody_saveKinematicState },
  { "applyGravity" , btRigidBody_applyGravity },
  { "setGravity"   , btRigidBody_setGravity },
  { "getGravity"   , btRigidBody_getGravity },
  { "setDamping"   , btRigidBody_setDamping },
  { "getLinearDamping", btRigidBody_getLinearDamping },
  { "getAngularDamping", btRigidBody_getAngularDamping },
  { "getLinearSleepingThreshold", btRigidBody_getLinearSleepingThreshold },
  { "getAngularSleepingThreshold", btRigidBody_getAngularSleepingThreshold },
  { "applyDamping" , btRigidBody_applyDamping },
  { "getCollisionShape", btRigidBody_getCollisionShape },
  { "setMassProps" , btRigidBody_setMassProps },
  { "getLinearFactor", btRigidBody_getLinearFactor },
  { "setLinearFactor", btRigidBody_setLinearFactor },
  { "getInvMass"   , btRigidBody_getInvMass },
  { "getInvInertiaTensorWorld", btRigidBody_getInvInertiaTensorWorld },
  { "integrateVelocities", btRigidBody_integrateVelocities },
  { "setCenterOfMassTransform", btRigidBody_setCenterOfMassTransform },
  { "applyCentralForce", btRigidBody_applyCentralForce },
  { "getTotalForce", btRigidBody_getTotalForce },
  { "getTotalTorque", btRigidBody_getTotalTorque },
  { "getInvInertiaDiagLocal", btRigidBody_getInvInertiaDiagLocal },
  { "setInvInertiaDiagLocal", btRigidBody_setInvInertiaDiagLocal },
  { "setSleepingThresholds", btRigidBody_setSleepingThresholds },
  { "applyTorque"  , btRigidBody_applyTorque },
  { "applyForce"   , btRigidBody_applyForce },
  { "applyCentralImpulse", btRigidBody_applyCentralImpulse },
  { "applyTorqueImpulse", btRigidBody_applyTorqueImpulse },
  { "applyImpulse" , btRigidBody_applyImpulse },
  { "clearForces"  , btRigidBody_clearForces },
  { "updateInertiaTensor", btRigidBody_updateInertiaTensor },
  { "getCenterOfMassPosition", btRigidBody_getCenterOfMassPosition },
  { "getOrientation", btRigidBody_getOrientation },
  { "getCenterOfMassTransform", btRigidBody_getCenterOfMassTransform },
  { "getLinearVelocity", btRigidBody_getLinearVelocity },
  { "getAngularVelocity", btRigidBody_getAngularVelocity },
  { "setLinearVelocity", btRigidBody_setLinearVelocity },
  { "setAngularVelocity", btRigidBody_setAngularVelocity },
  { "getVelocityInLocalPoint", btRigidBody_getVelocityInLocalPoint },
  { "translate"    , btRigidBody_translate },
  { "getAabb"      , btRigidBody_getAabb  },
  { "computeImpulseDenominator", btRigidBody_computeImpulseDenominator },
  { "computeAngularImpulseDenominator", btRigidBody_computeAngularImpulseDenominator },
  { "updateDeactivation", btRigidBody_updateDeactivation },
  { "wantsSleeping", btRigidBody_wantsSleeping },
  { "getBroadphaseProxy", btRigidBody_getBroadphaseProxy },
  { "setNewBroadphaseProxy", btRigidBody_setNewBroadphaseProxy },
  { "getMotionState", btRigidBody_getMotionState },
  { "setMotionState", btRigidBody_setMotionState },
  { "setAngularFactor", btRigidBody_setAngularFactor },
  { "getAngularFactor", btRigidBody_getAngularFactor },
  { "isInWorld"    , btRigidBody_isInWorld },
  { "checkCollideWithOverride", btRigidBody_checkCollideWithOverride },
  { "addConstraintRef", btRigidBody_addConstraintRef },
  { "removeConstraintRef", btRigidBody_removeConstraintRef },
  { "getConstraintRef", btRigidBody_getConstraintRef },
  { "getNumConstraintRefs", btRigidBody_getNumConstraintRefs },
  { "setFlags"     , btRigidBody_setFlags },
  { "getFlags"     , btRigidBody_getFlags },
  { "computeGyroscopicForce", btRigidBody_computeGyroscopicForce },
  { "calculateSerializeBufferSize", btRigidBody_calculateSerializeBufferSize },
  { "serialize"    , btRigidBody_serialize },
  { "serializeSingleObject", btRigidBody_serializeSingleObject },
  { "upcast"       , btRigidBody_upcast   },
  { "__tostring"   , btRigidBody___tostring },
  { "deleted"      , dub_isDeleted        },
  { NULL, NULL},
};


extern "C" int luaopen_bt_RigidBody(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "bt.RigidBody");
  // <mt>

  // register member methods
  luaL_register(L, NULL, btRigidBody_member_methods);
  // save meta-table in bt
  dub_register(L, "bt", "RigidBody", "RigidBody");
  // <mt>
  lua_pop(L, 1);
  return 0;
}
